package jogodavelha;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pedro
 */
public class Interf extends javax.swing.JFrame {

    String marca = "X";
    int marcaBin = 1;
    int matriz[][] = new int[3][3];
    int num = 0;
    int m, n;

    public Interf() {
        
        initComponents();
    }
    
    public void change(){
        if(marca.equals("X")) {
            marca = "O";
            marcaBin = 2;
        }else {
            marca = "X";
            marcaBin = 1;
        }
    
    }
    
    public void jogar(int i, int j, int x){
        num++;
        matriz[i][j] = x;
        
        switch (num){
        
            case 1:
                jogada1(i,j);
                
                break;
            case 2:
                jogada2(i,j);
                
                break;
            case 3:
                jogada3(i,j);
                
                break;
            case 4:
                jogada4(i,j);
                
                break;
                    
        
        }
        
    }
    
    public void jogada1(int i, int j){
        
        //Se jogou nos cantos ele joga no meio
        if(i == 0 && j == 0){ m = 1; n = 1;}
        else if(i == 0 && j == 2){ m = 1; n = 1;}
        else if(i == 2 && j == 0){ m = 1; n = 1;}
        else if(i == 2 && j == 2){ m = 1; n = 1;}
        else if(i == 1 && j == 1){ m = 0; n = 0;}
        else if(i == 0 && j == 1){ m = 1; n = 1;}
        else if(i == 1 && j == 0){ m = 1; n = 1;}
        else if(i == 1 && j == 2){ m = 1; n = 1;}
        else if(i == 2 && j == 1){ m = 1; n = 1;}
        
        
    }
    public void jogada2(int i, int j){
        
    }
    
    public void jogada3(int i, int j){
    }
    
    public void jogada4(int i, int j){
    }
    
    public void jogou(int k, int l){
        if(k == 0 && l == 0){Casa1.setText(marca); matriz[0][0] = marcaBin;}
        else if(k == 0 && l == 1){Casa2.setText(marca); matriz[0][1] = marcaBin;}
        else if(k == 0 && l == 2){Casa3.setText(marca); matriz[0][2] = marcaBin;}
        else if(k == 1 && l == 0){Casa4.setText(marca); matriz[1][0] = marcaBin;}
        else if(k == 1 && l == 1){Casa5.setText(marca); matriz[1][1] = marcaBin;}
        else if(k == 1 && l == 2){Casa6.setText(marca); matriz[1][2] = marcaBin;}
        else if(k == 2 && l == 0){Casa7.setText(marca); matriz[2][0] = marcaBin;}
        else if(k == 2 && l == 1){Casa8.setText(marca); matriz[2][1] = marcaBin;}
        else if(k == 2 && l == 2){Casa9.setText(marca); matriz[2][2] = marcaBin;}
        
        change();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Casa1 = new javax.swing.JButton();
        Casa2 = new javax.swing.JButton();
        Casa3 = new javax.swing.JButton();
        Casa4 = new javax.swing.JButton();
        Casa5 = new javax.swing.JButton();
        Casa6 = new javax.swing.JButton();
        Casa9 = new javax.swing.JButton();
        Casa8 = new javax.swing.JButton();
        Casa7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        restart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Casa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casa1ActionPerformed(evt);
            }
        });

        Casa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casa2ActionPerformed(evt);
            }
        });

        Casa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casa3ActionPerformed(evt);
            }
        });

        Casa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casa4ActionPerformed(evt);
            }
        });

        Casa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casa5ActionPerformed(evt);
            }
        });

        Casa6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casa6ActionPerformed(evt);
            }
        });

        Casa9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casa9ActionPerformed(evt);
            }
        });

        Casa8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casa8ActionPerformed(evt);
            }
        });

        Casa7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casa7ActionPerformed(evt);
            }
        });

        jLabel1.setText("Jogo da Velha");

        restart.setText("Restart");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Casa4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Casa1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Casa2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Casa5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Casa7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(restart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Casa8, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Casa9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Casa3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Casa6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel1)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Casa2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Casa1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Casa3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Casa4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Casa5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Casa6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Casa7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Casa8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Casa9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(restart)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Casa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casa1ActionPerformed
         
            if (Casa1.getText().equals("")) {
                Casa1.setText(marca);
                matriz[0][0] = marcaBin;
                jogar( 0, 0, marcaBin);
                change();
                jogou(m,n);
            }
    }//GEN-LAST:event_Casa1ActionPerformed

    private void Casa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casa2ActionPerformed
        if (Casa2.getText().equals("")) {
                Casa2.setText(marca);
                matriz[0][1] = marcaBin;
                jogar( 0, 1, marcaBin);
                change();
                jogou(m,n);
            }
    }//GEN-LAST:event_Casa2ActionPerformed

    private void Casa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casa3ActionPerformed
        if (Casa3.getText().equals("")) {
                Casa3.setText(marca);
                matriz[0][2] = marcaBin;
                jogar( 0, 2, marcaBin);
                change();
                jogou(m,n);
            }
    }//GEN-LAST:event_Casa3ActionPerformed

    private void Casa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casa4ActionPerformed
        if (Casa4.getText().equals("")) {
                Casa4.setText(marca);
                matriz[1][0] = marcaBin;
                jogar( 1, 0, marcaBin);
                change();
                jogou(m,n);
            }
    }//GEN-LAST:event_Casa4ActionPerformed

    private void Casa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casa5ActionPerformed
        if (Casa5.getText().equals("")) {
                Casa5.setText(marca);
                matriz[1][1] = marcaBin;
                jogar( 1, 1, marcaBin);
                change();
                jogou(m,n);
            }
    }//GEN-LAST:event_Casa5ActionPerformed

    private void Casa6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casa6ActionPerformed
        if (Casa6.getText().equals("")) {
                Casa6.setText(marca);
                matriz[1][2] = marcaBin;
                jogar( 1, 2, marcaBin);
                change();
                jogou(m,n);
            }
    }//GEN-LAST:event_Casa6ActionPerformed

    private void Casa7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casa7ActionPerformed
        if (Casa7.getText().equals("")) {
                Casa7.setText(marca);
                matriz[2][0] = marcaBin;
                jogar( 2, 0, marcaBin);
                change();
                jogou(m,n);
            }
    }//GEN-LAST:event_Casa7ActionPerformed

    private void Casa8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casa8ActionPerformed
        if (Casa8.getText().equals("")) {
                Casa8.setText(marca);
                matriz[2][1] = marcaBin;
                jogar( 2, 1, marcaBin);
                change();
                jogou(m,n);
            }
    }//GEN-LAST:event_Casa8ActionPerformed

    private void Casa9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casa9ActionPerformed
        if (Casa9.getText().equals("")) {
                Casa9.setText(marca);
                matriz[2][2] = marcaBin;
                jogar( 2, 2, marcaBin);
                change();
                jogou(m,n);
            }
        
    }//GEN-LAST:event_Casa9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Casa1;
    private javax.swing.JButton Casa2;
    private javax.swing.JButton Casa3;
    private javax.swing.JButton Casa4;
    private javax.swing.JButton Casa5;
    private javax.swing.JButton Casa6;
    private javax.swing.JButton Casa7;
    private javax.swing.JButton Casa8;
    private javax.swing.JButton Casa9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton restart;
    // End of variables declaration//GEN-END:variables
}
