package jogodavelha;


/**
 *
 * @author Pedro
 */
public class Interf extends javax.swing.JFrame {

    
    private static Interf interf;
    public Jogo p;
    private Interf() {
        
        initComponents();
    }
    
    public static Interf getInstance(){
        if (interf == null)
            interf = new Interf();
 
        return interf;
    }
    public void recebe(Jogo pu){
        p = pu;
    }
    
    public void jogou(String c, int k){
        
            if(k == 0 ){Casa1.setText(c); }
            else if(k == 1 ){Casa2.setText(c);}
            else if(k == 2 ){Casa3.setText(c);}
            else if(k == 3 ){Casa4.setText(c);}
            else if(k == 4 ){Casa5.setText(c);}
            else if(k == 5 ){Casa6.setText(c);}
            else if(k == 6 ){Casa7.setText(c);}
            else if(k == 7 ){Casa8.setText(c);}
            else if(k == 8 ){Casa9.setText(c);}
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Casa1 = new javax.swing.JButton();
        Casa2 = new javax.swing.JButton();
        Casa3 = new javax.swing.JButton();
        Casa4 = new javax.swing.JButton();
        Casa5 = new javax.swing.JButton();
        Casa6 = new javax.swing.JButton();
        Casa9 = new javax.swing.JButton();
        Casa8 = new javax.swing.JButton();
        Casa7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Casa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casa1ActionPerformed(evt);
            }
        });

        Casa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casa2ActionPerformed(evt);
            }
        });

        Casa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casa3ActionPerformed(evt);
            }
        });

        Casa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casa4ActionPerformed(evt);
            }
        });

        Casa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casa5ActionPerformed(evt);
            }
        });

        Casa6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casa6ActionPerformed(evt);
            }
        });

        Casa9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casa9ActionPerformed(evt);
            }
        });

        Casa8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casa8ActionPerformed(evt);
            }
        });

        Casa7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casa7ActionPerformed(evt);
            }
        });

        jLabel1.setText("Jogo da Velha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Casa4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Casa1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Casa2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Casa5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Casa7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Casa8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Casa9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Casa3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Casa6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Casa2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Casa1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Casa3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Casa4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Casa5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Casa6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Casa7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Casa8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Casa9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Casa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casa1ActionPerformed
                
        p.jogada(0,0);      
    }//GEN-LAST:event_Casa1ActionPerformed

    private void Casa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casa2ActionPerformed

        p.jogada(0,1);
      
    }//GEN-LAST:event_Casa2ActionPerformed

    private void Casa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casa3ActionPerformed
    
        p.jogada(0,2);
     
    }//GEN-LAST:event_Casa3ActionPerformed

    private void Casa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casa4ActionPerformed
  
        p.jogada(1,0);
      
    }//GEN-LAST:event_Casa4ActionPerformed

    private void Casa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casa5ActionPerformed
   
        p.jogada(1,1);
     
    }//GEN-LAST:event_Casa5ActionPerformed

    private void Casa6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casa6ActionPerformed
        p.jogada(1,2);

    }//GEN-LAST:event_Casa6ActionPerformed

    private void Casa7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casa7ActionPerformed

        p.jogada(2,0);
    }//GEN-LAST:event_Casa7ActionPerformed

    private void Casa8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casa8ActionPerformed
        
        p.jogada(2,1);     
    }//GEN-LAST:event_Casa8ActionPerformed

    private void Casa9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casa9ActionPerformed
        
        p.jogada(2,2);
                
                
                
            
        
    }//GEN-LAST:event_Casa9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Casa1;
    private javax.swing.JButton Casa2;
    private javax.swing.JButton Casa3;
    private javax.swing.JButton Casa4;
    private javax.swing.JButton Casa5;
    private javax.swing.JButton Casa6;
    private javax.swing.JButton Casa7;
    private javax.swing.JButton Casa8;
    private javax.swing.JButton Casa9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
